import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import clsx from "clsx";
import ThemeProvider from "@/components/theme/ThemeProvider";
import Navbar from "@/components/Navigation/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="h-full">
      <body className={clsx("bg-app-gray h-full")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col h-full">
            <Navbar />
            <div className="flex-1 m-auto px-12 py-36 w-full max-w-6xl">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
